sudo: required

language: cpp

before_install:
# We need this line to have g++4.8 available in apt
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  
install:	
  - sudo apt-get install -qq gcc-4.8 g++-4.8 
# We want to compile with g++ 4.8 when rather than the default g++
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
  - gcc -v
  - wget http://apt.biicode.com/install.sh
  - chmod +x install.sh
  - ./install.sh #Install biicode
  - bii setup:cpp #Install biicode required C/C++ tools (GCC, cmake, etc)
  - bii --version
  
script:
  - bii init -L
  - bii find --update #Find biicode dependencies 
  - bii cpp:configure #Configure block for building
  - bii cpp:build #Build block
  - ./bin/nick_cpp_ci_demo_tests --reporter=info #Run tests
  
deploy:
  provider: biicode
  user: nick
  password:
    secure: DYfsBNpCG5impyGgOcQtaFfkEEqC1XURQUlXxJG7xc3kLzpoUfmaZ/Eq7Wfs73OEevOaEqL9mMbbFWvQmD6Q5vt9yw6Hlx95TnwhWkwqNiiw8KJ+s8TPr8W5cHFPfU+5txNWruUzh0IxAgBNpBWFBoZH4etBZiY114YA3Yw7iho=
  on:
    repo: audioplastic/cpp_ci_demo #GitHub repo