sudo: required

language: cpp

compiler:
  - gcc
  - clang

before_install:
  - echo $LANG
  - echo $LC_ALL
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update && sudo apt-get install -y llvm-3.4 llvm-3.4-dev; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install llvm && brew link --force llvm; fi
  
install:
  - wget http://apt.biicode.com/install.sh
  - chmod +x install.sh
  - ./install.sh #Install biicode
  - bii setup:cpp #Install biicode required C/C++ tools (GCC, cmake, etc)
  - bii --version
  
before_script:
  - travis_retry bundle
  - if [ $TRAVIS_OS_NAME == linux ]; then travis_retry ./configure --llvm-config llvm-config-3.4; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then travis_retry ./configure --llvm-config /usr/local/opt/llvm/bin/llvm-config; fi
  
script:
  - bii init -L
  - bii find --update #Find biicode dependencies 
  - bii cpp:configure #Configure block for building
  - bii cpp:build #Build block
  - ./bin/nick_cpp_ci_demo_tests --reporter=info #Run tests
  
deploy:
  provider: biicode
  user: nick
  password:
    secure: DYfsBNpCG5impyGgOcQtaFfkEEqC1XURQUlXxJG7xc3kLzpoUfmaZ/Eq7Wfs73OEevOaEqL9mMbbFWvQmD6Q5vt9yw6Hlx95TnwhWkwqNiiw8KJ+s8TPr8W5cHFPfU+5txNWruUzh0IxAgBNpBWFBoZH4etBZiY114YA3Yw7iho=
  on:
    repo: audioplastic/cpp_ci_demo #GitHub repo